Put back auto and manual together

diff --git a/.github/workflows/soak-testing.yml b/.github/workflows/soak-testing.yml
--- a/.github/workflows/soak-testing.yml
+++ b/.github/workflows/soak-testing.yml
@@ -34,7 +34,7 @@ jobs:
       fail-fast: false
       matrix:
         app-platform: [ flask ]
-        instrumentation-type: [ manual ]
+        instrumentation-type: [ auto, manual ]
     env:
       # NOTE: `APP_PATH` configuration is repo dependent
       APP_PATH: integration-test-apps/${{ matrix.instrumentation-type}}-instrumentation/${{ matrix.app-platform }}
@@ -94,127 +94,124 @@ jobs:
             type=ref,event=branch
             type=ref,event=tag
             type=ref,event=pr
-      - name: DEBUG - Check what is in the app?
+      # TODO: Instead of building, publishing, and pulling a Sample App Docker Image in `docker-compose`. Could we
+      # just build the image in `docker-compose` directly using `build/context`? We would lose the public Docker Image
+      # but we would avoid polluting the published packages and anyone could build from the commit if they wanted to.
+      - name: Build and Push Docker image
+        uses: docker/build-push-action@v2
+        with:
+          push: true
+          context: ${{ env.APP_PATH }}
+          tags: ${{ steps.docker-image-metadata.outputs.tags }}
+          labels: ${{ steps.docker-image-metadata.outputs.labels }}
+          cache-from: type=local,src=/tmp/.buildx-cache
+          cache-to: type=local,dest=/tmp/.buildx-cache
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
+          role-duration-seconds: 21600 # 6 Hours
+          aws-region: ${{ env.AWS_DEFAULT_REGION }}
+      - name: Run All Docker Containers - Sample App + OTel Collector + Load Generator + Alarm Poller
+        id: check-failure-during-performance-tests
+        continue-on-error: true
+        working-directory: .github/docker-performance-tests
+        env:
+          APP_IMAGE: ${{ fromJSON(steps.docker-image-metadata.outputs.json).tags[0] }}
+          INSTANCE_ID: ${{ github.run_id }}-${{ github.run_number }}
+          LISTEN_ADDRESS: 0.0.0.0:8080
+          LOG_GROUP_NAME: otel-sdk-performance-tests
+          APP_PLATFORM: ${{ matrix.app-platform }}
+          INSTRUMENTATION_TYPE: ${{ matrix.instrumentation-type }}
+          # Also uses:
+          # LOGS_NAMESPACE
+          # LOG_STREAM_NAME
+          # APP_PROCESS_COMMAND_LINE_DIMENSION_VALUE
+          # APP_PROCESS_EXECUTABLE_NAME
+          # HOSTMETRICS_INTERVAL_SECS
+          # TEST_DURATION_MINUTES
+          # NUM_OF_CPUS
+          # CPU_LOAD_THRESHOLD
+          # TOTAL_MEMORY_THRESHOLD
+          # AWS_DEFAULT_REGION
+        run: >-
+          docker-compose up --build;
+          exit $(docker inspect $(docker ps --quiet --all --filter "name=docker-performance-tests_alarms-poller") --format="{{.State.ExitCode}}");
+      - name: Install script dependencies
+        run: pip install boto3
+      - name: Get a snapshot of metrics
+        run: python3 .github/scripts/performance-tests/produce-metric-widget-images.py
+          --cpu-load-threshold ${{ env.CPU_LOAD_THRESHOLD }}
+          --logs-namespace ${{ env.LOGS_NAMESPACE }}
+          --metrics-period ${{ env.HOSTMETRICS_INTERVAL_SECS }}
+          --num-of-cpus ${{ env.NUM_OF_CPUS }}
+          --app-process-command-line-dimension-value "${{ env.APP_PROCESS_COMMAND_LINE_DIMENSION_VALUE }}"
+          --total-memory-threshold ${{ env.TOTAL_MEMORY_THRESHOLD }}
+          --test-duration-minutes ${{ env.TEST_DURATION_MINUTES }}
+          --app-platform ${{ matrix.app-platform }}
+          --instrumentation-type ${{ matrix.instrumentation-type }}
+          --github-sha ${{ github.sha }}
+          --github-run-id $GITHUB_RUN_ID
+      - name: Commit snapshots to repository
         run: |-
-          ls -l ${{ env.APP_PATH }}
-      # # TODO: Instead of building, publishing, and pulling a Sample App Docker Image in `docker-compose`. Could we
-      # # just build the image in `docker-compose` directly using `build/context`? We would lose the public Docker Image
-      # # but we would avoid polluting the published packages and anyone could build from the commit if they wanted to.
-      # - name: Build and Push Docker image
-      #   uses: docker/build-push-action@v2
-      #   with:
-      #     push: true
-      #     context: ${{ env.APP_PATH }}
-      #     tags: ${{ steps.docker-image-metadata.outputs.tags }}
-      #     labels: ${{ steps.docker-image-metadata.outputs.labels }}
-      #     cache-from: type=local,src=/tmp/.buildx-cache
-      #     cache-to: type=local,dest=/tmp/.buildx-cache
-      # - name: Configure AWS Credentials
-      #   uses: aws-actions/configure-aws-credentials@v1
-      #   with:
-      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-      #     role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
-      #     role-duration-seconds: 21600 # 6 Hours
-      #     aws-region: ${{ env.AWS_DEFAULT_REGION }}
-      # - name: Run All Docker Containers - Sample App + OTel Collector + Load Generator + Alarm Poller
-      #   id: check-failure-during-performance-tests
-      #   continue-on-error: true
-      #   working-directory: .github/docker-performance-tests
-      #   env:
-      #     APP_IMAGE: ${{ fromJSON(steps.docker-image-metadata.outputs.json).tags[0] }}
-      #     INSTANCE_ID: ${{ github.run_id }}-${{ github.run_number }}
-      #     LISTEN_ADDRESS: 0.0.0.0:8080
-      #     LOG_GROUP_NAME: otel-sdk-performance-tests
-      #     APP_PLATFORM: ${{ matrix.app-platform }}
-      #     INSTRUMENTATION_TYPE: ${{ matrix.instrumentation-type }}
-      #     # Also uses:
-      #     # LOGS_NAMESPACE
-      #     # LOG_STREAM_NAME
-      #     # APP_PROCESS_COMMAND_LINE_DIMENSION_VALUE
-      #     # APP_PROCESS_EXECUTABLE_NAME
-      #     # HOSTMETRICS_INTERVAL_SECS
-      #     # TEST_DURATION_MINUTES
-      #     # NUM_OF_CPUS
-      #     # CPU_LOAD_THRESHOLD
-      #     # TOTAL_MEMORY_THRESHOLD
-      #     # AWS_DEFAULT_REGION
-      #   run: >-
-      #     docker-compose up --build;
-      #     exit $(docker inspect $(docker ps --quiet --all --filter "name=docker-performance-tests_alarms-poller") --format="{{.State.ExitCode}}");
-      # - name: Install script dependencies
-      #   run: pip install boto3
-      # - name: Get a snapshot of metrics
-      #   run: python3 .github/scripts/performance-tests/produce-metric-widget-images.py
-      #     --cpu-load-threshold ${{ env.CPU_LOAD_THRESHOLD }}
-      #     --logs-namespace ${{ env.LOGS_NAMESPACE }}
-      #     --metrics-period ${{ env.HOSTMETRICS_INTERVAL_SECS }}
-      #     --num-of-cpus ${{ env.NUM_OF_CPUS }}
-      #     --app-process-command-line-dimension-value "${{ env.APP_PROCESS_COMMAND_LINE_DIMENSION_VALUE }}"
-      #     --total-memory-threshold ${{ env.TOTAL_MEMORY_THRESHOLD }}
-      #     --test-duration-minutes ${{ env.TEST_DURATION_MINUTES }}
-      #     --app-platform ${{ matrix.app-platform }}
-      #     --instrumentation-type ${{ matrix.instrumentation-type }}
-      #     --github-sha ${{ github.sha }}
-      #     --github-run-id $GITHUB_RUN_ID
-      # - name: Commit snapshots to repository
-      #   run: |-
-      #     git config user.email "41898282+github-actions[bot]@users.noreply.github.com";
-      #     git config user.name "GitHub Actions";
-      #     git checkout main;
-      #     git pull;
-      #     git checkout gh-pages;
-      #     git add soak-tests/snapshots;
-      #     git commit -m "Adding Soak Tests Snapshots from ${{ github.sha }}";
-      #     git push;
-      # - name: Move back to the main branch
-      #   run: git checkout main
-      # - name: Prepare Performance Test results as JSON output
-      #   run: python3 .github/scripts/performance-tests/produce-performance-test-results.py
-      #     --cpu-load-threshold ${{ env.CPU_LOAD_THRESHOLD }}
-      #     --logs-namespace ${{ env.LOGS_NAMESPACE }}
-      #     --metrics-period ${{ env.HOSTMETRICS_INTERVAL_SECS }}
-      #     --num-of-cpus ${{ env.NUM_OF_CPUS }}
-      #     --app-process-command-line-dimension-value "${{ env.APP_PROCESS_COMMAND_LINE_DIMENSION_VALUE }}"
-      #     --total-memory-threshold ${{ env.TOTAL_MEMORY_THRESHOLD }}
-      #     --test-duration-minutes ${{ env.TEST_DURATION_MINUTES }}
-      # - name: Report on Performance Test Averages results
-      #   uses: NathanielRN/github-action-benchmark@v1.8.2-alpha3
-      #   continue-on-error: true
-      #   id: check-failure-after-performance-tests
-      #   with:
-      #     name: Soak Test Results - sample-app-${{ matrix.app-platform }}-${{ matrix.instrumentation-type }}
-      #     tool: custombenchmark
-      #     output-file-path: output.json
-      #     github-token: ${{ secrets.GITHUB_TOKEN }}
-      #     max-items-in-chart: 100
-      #     alert-threshold: 1% #175%
-      #     # Does not work as expected, see: https://github.com/open-telemetry/opentelemetry-python/pull/1478
-      #     # comment-always: true
-      #     fail-on-alert: true
-      #     auto-push: ${{ github.ref == 'refs/heads/main' }}
-      #     gh-pages-branch: gh-pages
-      #     benchmark-data-dir-path: soak-tests/per-commit-overall-results
-      # - name: Publish Issue if failed DURING Performance Tests
-      #   uses: JasonEtco/create-an-issue@v2
-      #   if: steps.check-failure-during-performance-tests.outcome == 'failure'
-      #   env:
-      #     APP_PLATFORM: ${{ matrix.app-platform }}
-      #     INSTRUMENTATION_TYPE: ${{ matrix.instrumentation-type }}
-      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      #   with:
-      #     filename: .github/issue-templates/FAILURE-DURING-SOAK_TESTS.md
-      # - name: Publish Issue if failed AFTER Performance Tests
-      #   uses: JasonEtco/create-an-issue@v2
-      #   if: steps.check-failure-after-performance-tests.outcome == 'failure'
-      #   env:
-      #     APP_PLATFORM: ${{ matrix.app-platform }}
-      #     INSTRUMENTATION_TYPE: ${{ matrix.instrumentation-type }}
-      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      #   with:
-      #     filename: .github/issue-templates/FAILURE-AFTER-SOAK_TESTS.md
-      # - name: Check for Performance Degradation either DURING or AFTER Performance Tests
-      #   if: steps.check-failure-during-performance-tests.outcome == 'failure' || steps.check-failure-after-performance-tests.outcome == 'failure'
-      #   run: >-
-      #     echo 'Performance Tests failed, see the logs above for details';
-      #     exit 1;
+          git config user.email "41898282+github-actions[bot]@users.noreply.github.com";
+          git config user.name "GitHub Actions";
+          git checkout main;
+          git pull;
+          git checkout gh-pages;
+          git add soak-tests/snapshots;
+          git commit -m "Adding Soak Tests Snapshots from ${{ github.sha }}";
+          git push;
+      - name: Move back to the main branch
+        run: git checkout main
+      - name: Prepare Performance Test results as JSON output
+        run: python3 .github/scripts/performance-tests/produce-performance-test-results.py
+          --cpu-load-threshold ${{ env.CPU_LOAD_THRESHOLD }}
+          --logs-namespace ${{ env.LOGS_NAMESPACE }}
+          --metrics-period ${{ env.HOSTMETRICS_INTERVAL_SECS }}
+          --num-of-cpus ${{ env.NUM_OF_CPUS }}
+          --app-process-command-line-dimension-value "${{ env.APP_PROCESS_COMMAND_LINE_DIMENSION_VALUE }}"
+          --total-memory-threshold ${{ env.TOTAL_MEMORY_THRESHOLD }}
+          --test-duration-minutes ${{ env.TEST_DURATION_MINUTES }}
+      - name: Report on Performance Test Averages results
+        uses: NathanielRN/github-action-benchmark@v1.8.2-alpha3
+        continue-on-error: true
+        id: check-failure-after-performance-tests
+        with:
+          name: Soak Test Results - sample-app-${{ matrix.app-platform }}-${{ matrix.instrumentation-type }}
+          tool: custombenchmark
+          output-file-path: output.json
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          max-items-in-chart: 100
+          alert-threshold: 1% #175%
+          # Does not work as expected, see: https://github.com/open-telemetry/opentelemetry-python/pull/1478
+          # comment-always: true
+          fail-on-alert: true
+          auto-push: ${{ github.ref == 'refs/heads/main' }}
+          gh-pages-branch: gh-pages
+          benchmark-data-dir-path: soak-tests/per-commit-overall-results
+      - name: Publish Issue if failed DURING Performance Tests
+        uses: JasonEtco/create-an-issue@v2
+        if: steps.check-failure-during-performance-tests.outcome == 'failure'
+        env:
+          APP_PLATFORM: ${{ matrix.app-platform }}
+          INSTRUMENTATION_TYPE: ${{ matrix.instrumentation-type }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          filename: .github/issue-templates/FAILURE-DURING-SOAK_TESTS.md
+      - name: Publish Issue if failed AFTER Performance Tests
+        uses: JasonEtco/create-an-issue@v2
+        if: steps.check-failure-after-performance-tests.outcome == 'failure'
+        env:
+          APP_PLATFORM: ${{ matrix.app-platform }}
+          INSTRUMENTATION_TYPE: ${{ matrix.instrumentation-type }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          filename: .github/issue-templates/FAILURE-AFTER-SOAK_TESTS.md
+      - name: Check for Performance Degradation either DURING or AFTER Performance Tests
+        if: steps.check-failure-during-performance-tests.outcome == 'failure' || steps.check-failure-after-performance-tests.outcome == 'failure'
+        run: >-
+          echo 'Performance Tests failed, see the logs above for details';
+          exit 1;
