Some formatting fixes

diff --git a/.github/workflows/soak-testing.yml b/.github/workflows/soak-testing.yml
--- a/.github/workflows/soak-testing.yml
+++ b/.github/workflows/soak-testing.yml
@@ -76,7 +76,7 @@ jobs:
             type=ref,event=branch
             type=ref,event=tag
             type=ref,event=pr
-      # TODO: Instead of building, publishing, and pulling a Sample App Docker IMage in `docker-compose`. Could we
+      # TODO: Instead of building, publishing, and pulling a Sample App Docker Image in `docker-compose`. Could we
       # just build the image in `docker-compose` directly using `build/context`? We would lose the public Docker Image
       # but we would avoid polluting the published packages and anyone could build from the commit if they wanted to.
       - name: Build and Push Docker image
@@ -105,92 +105,93 @@ jobs:
           INSTANCE_ID: ${{ github.run_id }}-${{ github.run_number }}
           LISTEN_ADDRESS: 0.0.0.0:8080
           LOG_GROUP_NAME: otel-sdk-performance-tests
-          # LOGS_NAMESPACE: ${{ env.LOGS_NAMESPACE }}
-          # LOG_STREAM_NAME: ${{ env.IMAGE_SUFFIX }}
-          # PROCESS_COMMAND_LINE_DIMENSION_VALUE: ${{ env.PROCESS_COMMAND_LINE_DIMENSION_VALUE }}
-          # PROCESS_EXECUTABLE_NAME: ${{ env.PROCESS_EXECUTABLE_NAME }}
-          # HOSTMETRICS_INTERVAL_SECS: ${{ env.HOSTMETRICS_INTERVAL_SECS }}
-          # TEST_DURATION_MINUTES: ${{ env.TEST_DURATION_MINUTES }}
-          # NUM_OF_CPUS: ${{ env.NUM_OF_CPUS }}
-          # CPU_LOAD_THRESHOLD: ${{ env.CPU_LOAD_THRESHOLD }}
-          # TOTAL_MEMORY_THRESHOLD: ${{ env.TOTAL_MEMORY_THRESHOLD }}
-          # AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}
+          # Also uses:
+          # LOGS_NAMESPACE
+          # LOG_STREAM_NAME
+          # PROCESS_COMMAND_LINE_DIMENSION_VALUE
+          # PROCESS_EXECUTABLE_NAME
+          # HOSTMETRICS_INTERVAL_SECS
+          # TEST_DURATION_MINUTES
+          # NUM_OF_CPUS
+          # CPU_LOAD_THRESHOLD
+          # TOTAL_MEMORY_THRESHOLD
+          # AWS_DEFAULT_REGION
         run: >-
-          docker-compose up;
+          docker-compose up --build;
           exit $(docker inspect $(docker ps --quiet --all --filter "name=docker-performance-tests_alarms-poller") --format="{{.State.ExitCode}}");
-      # - name: Install script dependencies
-      #   run: pip install boto3
-      # - name: Get a snapshot of metrics
-      #   run: python3 .github/scripts/performance-tests/produce-metric-widget-images.py
-      #     --cpu-load-threshold ${{ env.CPU_LOAD_THRESHOLD }}
-      #     --logs-namespace ${{ env.LOGS_NAMESPACE }}
-      #     --metrics-period ${{ env.HOSTMETRICS_INTERVAL_SECS }}
-      #     --num-of-cpus ${{ env.NUM_OF_CPUS }}
-      #     --process-command-line-dimension-value "${{ env.PROCESS_COMMAND_LINE_DIMENSION_VALUE }}"
-      #     --test-duration-minutes ${{ env.TEST_DURATION_MINUTES }}
-      #     --total-memory-threshold ${{ env.TOTAL_MEMORY_THRESHOLD }}
-      #     --app-platform ${{ matrix.app-platform }}
-      #     --github-sha ${{ github.sha }}
-      #     --github-run-id $GITHUB_RUN_ID
-      #     --instrumentation-type ${{ matrix.instrumentation-type }}
-      # - name: Commit snapshots to repository
-      #   run: |-
-      #     git config user.email "41898282+github-actions[bot]@users.noreply.github.com";
-      #     git config user.name "GitHub Actions";
-      #     git checkout main;
-      #     git pull;
-      #     git checkout gh-pages;
-      #     git add soak-tests/snapshots;
-      #     git commit -m "Adding Soak Tests Snapshots from ${{ github.sha }}";
-      #     git push;
-      # - name: Move back to the main branch
-      #   run: git checkout main
-      # - name: Prepare Performance Test results as JSON output
-      #   run: python3 .github/scripts/performance-tests/produce-performance-test-results.py
-      #     --cpu-load-threshold ${{ env.CPU_LOAD_THRESHOLD }}
-      #     --logs-namespace ${{ env.LOGS_NAMESPACE }}
-      #     --metrics-period ${{ env.HOSTMETRICS_INTERVAL_SECS }}
-      #     --num-of-cpus ${{ env.NUM_OF_CPUS }}
-      #     --process-command-line-dimension-value "${{ env.PROCESS_COMMAND_LINE_DIMENSION_VALUE }}"
-      #     --test-duration-minutes ${{ env.TEST_DURATION_MINUTES }}
-      #     --total-memory-threshold ${{ env.TOTAL_MEMORY_THRESHOLD }}
-      # - name: Report on Performance Test Averages results
-      #   uses: NathanielRN/github-action-benchmark@v1.8.2-alpha3
-      #   continue-on-error: true
-      #   id: check-failure-after-performance-tests
-      #   with:
-      #     name: Soak Test Results - sample-app-${{ matrix.app-platform }}-${{ matrix.instrumentation-type }}
-      #     tool: custombenchmark
-      #     output-file-path: output.json
-      #     github-token: ${{ secrets.GITHUB_TOKEN }}
-      #     max-items-in-chart: 100
-      #     alert-threshold: 1% #175%
-      #     # Does not work as expected, see: https://github.com/open-telemetry/opentelemetry-python/pull/1478
-      #     # comment-always: true
-      #     fail-on-alert: true
-      #     auto-push: ${{ github.ref == 'refs/heads/main' }}
-      #     gh-pages-branch: gh-pages
-      #     benchmark-data-dir-path: soak-tests/per-commit-overall-results
-      # - name: Publish Issue if failed DURING Performance Tests
-      #   uses: JasonEtco/create-an-issue@v2
-      #   if: steps.check-failure-during-performance-tests.outcome == 'failure'
-      #   env:
-      #     APP_PLATFORM: ${{ matrix.app-platform }}
-      #     INSTRUMENTATION_TYPE: ${{ matrix.instrumentation-type }}
-      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      #   with:
-      #     filename: .github/issue-templates/FAILURE-DURING-SOAK_TESTS.md
-      # - name: Publish Issue if failed AFTER Performance Tests
-      #   uses: JasonEtco/create-an-issue@v2
-      #   if: steps.check-failure-after-performance-tests.outcome == 'failure'
-      #   env:
-      #     APP_PLATFORM: ${{ matrix.app-platform }}
-      #     INSTRUMENTATION_TYPE: ${{ matrix.instrumentation-type }}
-      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      #   with:
-      #     filename: .github/issue-templates/FAILURE-AFTER-SOAK_TESTS.md
-      # - name: Check for Performance Degradation either DURING or AFTER Performance Tests
-      #   if: steps.check-failure-during-performance-tests.outcome == 'failure' || steps.check-failure-after-performance-tests.outcome == 'failure'
-      #   run: >-
-      #     echo 'Performance Tests failed, see the logs above for details';
-      #     exit 1;
+      - name: Install script dependencies
+        run: pip install boto3
+      - name: Get a snapshot of metrics
+        run: python3 .github/scripts/performance-tests/produce-metric-widget-images.py
+          --cpu-load-threshold ${{ env.CPU_LOAD_THRESHOLD }}
+          --logs-namespace ${{ env.LOGS_NAMESPACE }}
+          --metrics-period ${{ env.HOSTMETRICS_INTERVAL_SECS }}
+          --num-of-cpus ${{ env.NUM_OF_CPUS }}
+          --process-command-line-dimension-value "${{ env.PROCESS_COMMAND_LINE_DIMENSION_VALUE }}"
+          --test-duration-minutes ${{ env.TEST_DURATION_MINUTES }}
+          --total-memory-threshold ${{ env.TOTAL_MEMORY_THRESHOLD }}
+          --app-platform ${{ matrix.app-platform }}
+          --github-sha ${{ github.sha }}
+          --github-run-id $GITHUB_RUN_ID
+          --instrumentation-type ${{ matrix.instrumentation-type }}
+      - name: Commit snapshots to repository
+        run: |-
+          git config user.email "41898282+github-actions[bot]@users.noreply.github.com";
+          git config user.name "GitHub Actions";
+          git checkout main;
+          git pull;
+          git checkout gh-pages;
+          git add soak-tests/snapshots;
+          git commit -m "Adding Soak Tests Snapshots from ${{ github.sha }}";
+          git push;
+      - name: Move back to the main branch
+        run: git checkout main
+      - name: Prepare Performance Test results as JSON output
+        run: python3 .github/scripts/performance-tests/produce-performance-test-results.py
+          --cpu-load-threshold ${{ env.CPU_LOAD_THRESHOLD }}
+          --logs-namespace ${{ env.LOGS_NAMESPACE }}
+          --metrics-period ${{ env.HOSTMETRICS_INTERVAL_SECS }}
+          --num-of-cpus ${{ env.NUM_OF_CPUS }}
+          --process-command-line-dimension-value "${{ env.PROCESS_COMMAND_LINE_DIMENSION_VALUE }}"
+          --test-duration-minutes ${{ env.TEST_DURATION_MINUTES }}
+          --total-memory-threshold ${{ env.TOTAL_MEMORY_THRESHOLD }}
+      - name: Report on Performance Test Averages results
+        uses: NathanielRN/github-action-benchmark@v1.8.2-alpha3
+        continue-on-error: true
+        id: check-failure-after-performance-tests
+        with:
+          name: Soak Test Results - sample-app-${{ matrix.app-platform }}-${{ matrix.instrumentation-type }}
+          tool: custombenchmark
+          output-file-path: output.json
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          max-items-in-chart: 100
+          alert-threshold: 1% #175%
+          # Does not work as expected, see: https://github.com/open-telemetry/opentelemetry-python/pull/1478
+          # comment-always: true
+          fail-on-alert: true
+          auto-push: ${{ github.ref == 'refs/heads/main' }}
+          gh-pages-branch: gh-pages
+          benchmark-data-dir-path: soak-tests/per-commit-overall-results
+      - name: Publish Issue if failed DURING Performance Tests
+        uses: JasonEtco/create-an-issue@v2
+        if: steps.check-failure-during-performance-tests.outcome == 'failure'
+        env:
+          APP_PLATFORM: ${{ matrix.app-platform }}
+          INSTRUMENTATION_TYPE: ${{ matrix.instrumentation-type }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          filename: .github/issue-templates/FAILURE-DURING-SOAK_TESTS.md
+      - name: Publish Issue if failed AFTER Performance Tests
+        uses: JasonEtco/create-an-issue@v2
+        if: steps.check-failure-after-performance-tests.outcome == 'failure'
+        env:
+          APP_PLATFORM: ${{ matrix.app-platform }}
+          INSTRUMENTATION_TYPE: ${{ matrix.instrumentation-type }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          filename: .github/issue-templates/FAILURE-AFTER-SOAK_TESTS.md
+      - name: Check for Performance Degradation either DURING or AFTER Performance Tests
+        if: steps.check-failure-during-performance-tests.outcome == 'failure' || steps.check-failure-after-performance-tests.outcome == 'failure'
+        run: >-
+          echo 'Performance Tests failed, see the logs above for details';
+          exit 1;
