Move back to main branch before 2nd results publish

diff --git a/.github/workflows/soak-testing.yml b/.github/workflows/soak-testing.yml
--- a/.github/workflows/soak-testing.yml
+++ b/.github/workflows/soak-testing.yml
@@ -21,7 +21,7 @@ jobs:
       contents: write
       packages: write
     strategy:
-      fail-fast: true
+      fail-fast: false
       matrix:
         app-platform: [ flask ]
         # instrumentation-type: [ auto, manual ]
@@ -32,65 +32,80 @@ jobs:
     steps:
       - uses: actions/checkout@v2
       # Only for manual app
-      - uses: actions/checkout@v2
-        if: ${{ matrix.instrumentation-type }} == manual
-        with:
-          repository: open-telemetry/opentelemetry-python
-          path: ${{ env.APP_PATH }}/opentelemetry-python-core
-      - uses: actions/checkout@v2
-        if: ${{ matrix.instrumentation-type }} == manual
-        with:
-          repository: open-telemetry/opentelemetry-python-contrib
-          path: ${{ env.APP_PATH }}/opentelemetry-python-contrib
-      - name: Log in to the GitHub Container Registry
-        uses: docker/login-action@v1
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v1
-      - name: Cache Docker layers
-        uses: actions/cache@v2
-        with:
-          path: /tmp/.buildx-cache
-          key: ${{ runner.os }}-buildx-${{ github.sha }}
-          restore-keys: |
-            ${{ runner.os }}-buildx-
-      - name: Extract metadata (tags, labels) for Docker
-        id: docker-image-metadata
-        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
-        with:
-          images: ghcr.io/${{ github.repository }}-${{ env.IMAGE_SUFFIX }}
-      - name: Build and Push Docker image
-        uses: docker/build-push-action@v2
-        with:
-          push: true
-          context: ${{ env.APP_PATH }}
-          tags: ${{ steps.docker-image-metadata.outputs.tags }}
-          labels: ${{ steps.docker-image-metadata.outputs.labels }}
-          cache-from: type=local,src=/tmp/.buildx-cache
-          cache-to: type=local,dest=/tmp/.buildx-cache
+      # - uses: actions/checkout@v2
+      #   if: ${{ matrix.instrumentation-type }} == manual
+      #   with:
+      #     repository: open-telemetry/opentelemetry-python
+      #     path: ${{ env.APP_PATH }}/opentelemetry-python-core
+      # - uses: actions/checkout@v2
+      #   if: ${{ matrix.instrumentation-type }} == manual
+      #   with:
+      #     repository: open-telemetry/opentelemetry-python-contrib
+      #     path: ${{ env.APP_PATH }}/opentelemetry-python-contrib
+      # - name: Log in to the GitHub Container Registry
+      #   uses: docker/login-action@v1
+      #   with:
+      #     registry: ghcr.io
+      #     username: ${{ github.actor }}
+      #     password: ${{ secrets.GITHUB_TOKEN }}
+      # - name: Set up Docker Buildx
+      #   uses: docker/setup-buildx-action@v1
+      # - name: Cache Docker layers
+      #   uses: actions/cache@v2
+      #   with:
+      #     path: /tmp/.buildx-cache
+      #     key: ${{ runner.os }}-buildx-${{ github.sha }}
+      #     restore-keys: |
+      #       ${{ runner.os }}-buildx-
+      # - name: Extract metadata (tags, labels) for Docker
+      #   id: docker-image-metadata
+      #   uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
+      #   with:
+      #     images: ghcr.io/${{ github.repository }}-${{ env.IMAGE_SUFFIX }}
+      # - name: Build and Push Docker image
+      #   uses: docker/build-push-action@v2
+      #   with:
+      #     push: true
+      #     context: ${{ env.APP_PATH }}
+      #     tags: ${{ steps.docker-image-metadata.outputs.tags }}
+      #     labels: ${{ steps.docker-image-metadata.outputs.labels }}
+      #     cache-from: type=local,src=/tmp/.buildx-cache
+      #     cache-to: type=local,dest=/tmp/.buildx-cache
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ env.AWS_REGION }}
-      - name: Run Sample App & OTel Collector + Load Generator
-        working-directory: .github/collector
-        env:
-          APP_IMAGE: ${{ steps.docker-image-metadata.outputs.tags }}
-          INSTANCE_ID: ${{ github.run_id }}-${{ github.run_number }}
-          LISTEN_ADDRESS: 0.0.0.0:8080
-          LOG_GROUP_NAME: ${{ github.repository }}/soak-tests
-          LOGS_NAMESPACE: ${{ github.repository }}/soak-tests
-          LOG_STREAM_NAME: ${{ env.IMAGE_SUFFIX }}
-          PROCESS_COMMAND_LINE: ${{ env.PROCESS_COMMAND_LINE }}
-          PROCESS_EXECUTABLE_NAME: ${{ env.PROCESS_EXECUTABLE_NAME }}
-          HOSTMETRICS_COLLECTION_INTERVAL_IN_SECONDS: ${{ env.HOSTMETRICS_COLLECTION_INTERVAL_IN_SECONDS }}s
-          SOAK_TEST_DURATION: ${{ env.HOURS_TO_RUN }}h
-        run: docker-compose up --abort-on-container-exit
+      # - name: Run Sample App & OTel Collector + Load Generator
+      #   working-directory: .github/collector
+      #   env:
+      #     APP_IMAGE: ${{ steps.docker-image-metadata.outputs.tags }}
+      #     INSTANCE_ID: ${{ github.run_id }}-${{ github.run_number }}
+      #     LISTEN_ADDRESS: 0.0.0.0:8080
+      #     LOG_GROUP_NAME: ${{ github.repository }}/soak-tests
+      #     LOGS_NAMESPACE: ${{ github.repository }}/soak-tests
+      #     LOG_STREAM_NAME: ${{ env.IMAGE_SUFFIX }}
+      #     PROCESS_COMMAND_LINE: ${{ env.PROCESS_COMMAND_LINE }}
+      #     PROCESS_EXECUTABLE_NAME: ${{ env.PROCESS_EXECUTABLE_NAME }}
+      #     HOSTMETRICS_COLLECTION_INTERVAL_IN_SECONDS: ${{ env.HOSTMETRICS_COLLECTION_INTERVAL_IN_SECONDS }}s
+      #     SOAK_TEST_DURATION: ${{ env.HOURS_TO_RUN }}h
+      #   run: docker-compose up --abort-on-container-exit
+      # Not possible...
+          # run: docker-compose up -d --abort-on-container-exit
+      # - name: Poll alarms during Soak Test
+      #   continue-on-error: true
+      #   run: >-
+      #     while [ pgrep docker-compose ];
+      #     do
+      #       if [ aws cloudwatch describe-alarms ];
+      #         echo 'Failed with: ';
+      #         echo "::set-output name=FAILED_DURING_SOAK_TESTS::True"
+      #         exit 1;
+      #       fi;
+      #       sleep ${{ env.HOSTMETRICS_COLLECTION_INTERVAL_IN_SECONDS }}s;
+      #     done
+      #   id: check-failure-during-soak-tests
       - name: Get number of CPUs
         run: echo "::set-output name=NUM_OF_CPUS::$(nproc --all)"
         id: get-num-of-cpus-step
@@ -116,6 +131,8 @@ jobs:
           add: soak-tests/snapshots
           branch: gh-pages
           message: 'Adding Soak Tests Snapshots'
+      - name: Move back to the main branch
+        run: git checkout main
       - name: Prepare Soak Test results as JSON output
         run: >-
           COMMON_API_PARAMETERS="
@@ -151,6 +168,7 @@ jobs:
           tee output.json
       - name: Report on Soak Test Averages results
         uses: NathanielRN/github-action-benchmark@v1.8.2-alpha3
+        continue-on-error: true
         with:
           name: Soak Test Results - sample-app-${{ matrix.app-platform }}-${{ matrix.instrumentation-type }}
           tool: custombenchmark
@@ -160,7 +178,29 @@ jobs:
           alert-threshold: 200%
           # Does not work as expected, see: https://github.com/open-telemetry/opentelemetry-python/pull/1478
           # comment-always: true
-          # fail-on-alert: true
+          fail-on-alert: true
           auto-push: ${{ github.ref == 'refs/heads/main' }}
           gh-pages-branch: gh-pages
           benchmark-data-dir-path: soak-tests/per-commit-overall-results
+        id: check-failure-after-soak-tests
+      # - name: Publish Issue if failed during Soak Tests
+      #   uses: JasonEtco/create-an-issue@v2
+      #   if: steps.check-failure-after-soak-tests.outcome == 'failure'
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      #   with:
+      #     filename: .github/issue-templates/FAILURE-DURING-SOAK-TESTS.md
+      #     update_existing: true
+      # - name: Publish Issue if failed after Soak Tests
+      #   uses: JasonEtco/create-an-issue@v2
+      #   if: steps.check-failure-after-soak-tests.outcome == 'failure'
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      #   with:
+      #     filename: .github/issue-templates/FAILURE-AFTER-SOAK-TESTS.md
+      #     update_existing: true
+      # - name: Determine if should fail the workflow
+      #   if: ${{ failure() }}
+      #   run: >-
+      #     echo 'Soak Tests failed, see logs for details';
+      #     exit 1;
