Print docker containers for debug

diff --git a/.github/workflows/soak-testing.yml b/.github/workflows/soak-testing.yml
--- a/.github/workflows/soak-testing.yml
+++ b/.github/workflows/soak-testing.yml
@@ -86,98 +86,99 @@ jobs:
         id: check-failure-during-soak-tests
         run: >-
           pip install docker;
+          python3 -c "import docker; client = docker.from_env(); print([c.name for c in client.containers.list(filters={'status': 'running'})]);"
           python3 ./.github/scripts/poll-during-soak-tests.py --polling-interval ${{ env.HOSTMETRICS_COLLECTION_INTERVAL_IN_SECONDS }};
-      - name: Get number of CPUs
-        run: echo "::set-output name=NUM_OF_CPUS::$(nproc --all)"
-        id: get-num-of-cpus-step
-      - name: Get a snapshot of metrics
-        run: >-
-          mkdir -p soak-tests/snapshots/${{ github.sha }};
-          for metric_kind in cpu-load memory-usage;
-          do
-            aws cloudwatch get-metric-widget-image --metric-widget "$(
-              cat ./.github/aws-cloudwatch-api-values/get-metric-widget-statistics/$metric_kind-metric-widget.json |
-              sed -e "s/<MINUTES_TO_RUN>/${{ env.MINUTES_TO_RUN }}/g" \
-                  -e "s/<METRIC_PERIOD>/${{ env.HOSTMETRICS_COLLECTION_INTERVAL_IN_SECONDS }}/g" \
-                  -e "s/<NUM_OF_CPUS>/${{ steps.get-num-of-cpus-step.outputs.NUM_OF_CPUS }}/g" \
-                  -e "s/<LOGS_NAMESPACE>/$(echo ${{ github.repository }}/soak-tests | sed 's/\//\\\//g')/g" \
-                  -e "s/<DIMENSION_1_VALUE>/$(echo ${{ env.PROCESS_COMMAND_LINE }} | sed 's/\//\\\//g')/g"
-            )" |
-            jq -r '.MetricWidgetImage' |
-            base64 -d > soak-tests/snapshots/${{ github.sha }}/${{ matrix.app-platform }}-${{ matrix.instrumentation-type }}-$metric_kind-results.png;
-          done
-      - name: Commit snapshots to repository
-        uses: EndBug/add-and-commit@v7
-        with:
-          add: soak-tests/snapshots
-          branch: gh-pages
-          message: 'Adding Soak Tests Snapshots'
-      - name: Move back to the main branch
-        run: git checkout main
-      - name: Prepare Soak Test results as JSON output
-        run: >-
-          declare -a COMMON_API_PARAMETERS=(
-          --namespace ${{ github.repository }}/soak-tests
-          --start-time $(date -u -d '${{ env.MINUTES_TO_RUN }} minutes ago' +%FT%TZ)
-          --end-time $(date -u +%FT%TZ)
-          --period ${{ env.HOSTMETRICS_COLLECTION_INTERVAL_IN_SECONDS }}
-          --region ${{ env.AWS_REGION }}
-          --statistics Sum
-          --dimensions Name=process.command_line,Value='${{ env.PROCESS_COMMAND_LINE }}'
-          );
-          AVERAGE_CPU_LOAD=$(
-            aws cloudwatch get-metric-statistics "${COMMON_API_PARAMETERS[@]}" --metric-name process.cpu.time |
-            jq -r '{
-              Name: "Soak Test Average CPU Load",
-              Value: [.Datapoints[].Sum] | (add / length / ${{ env.HOSTMETRICS_COLLECTION_INTERVAL_IN_SECONDS }} / ${{ steps.get-num-of-cpus-step.outputs.NUM_OF_CPUS }} * 100),
-              Unit: "Percent"
-            }'
-          )
-          AVERAGE_VIRTUAL_MEMORY=$(
-            aws cloudwatch get-metric-statistics "${COMMON_API_PARAMETERS[@]}" --metric-name process.memory.virtual_usage |
-            jq -r "{
-              Name: \"Soak Test Average Virtual Memory Used\",
-              Value: [.Datapoints[].Sum] | (add / length / $(echo '2^20' | bc)),
-              Unit: \"Megabytes\"
-            }"
-          );
-          jq -n "[$AVERAGE_CPU_LOAD] + [$AVERAGE_VIRTUAL_MEMORY] | {benchmarks: .}" |
-          tee output.json
-      - name: Report on Soak Test Averages results
-        uses: NathanielRN/github-action-benchmark@v1.8.2-alpha3
-        continue-on-error: true
-        id: check-failure-after-soak-tests
-        with:
-          name: Soak Test Results - sample-app-${{ matrix.app-platform }}-${{ matrix.instrumentation-type }}
-          tool: custombenchmark
-          output-file-path: output.json
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          max-items-in-chart: 100
-          alert-threshold: 1%
-          # Does not work as expected, see: https://github.com/open-telemetry/opentelemetry-python/pull/1478
-          # comment-always: true
-          fail-on-alert: true
-          auto-push: ${{ github.ref == 'refs/heads/main' }}
-          gh-pages-branch: gh-pages
-          benchmark-data-dir-path: soak-tests/per-commit-overall-results
-      - name: Publish Issue if failed DURING Soak Tests
-        uses: JasonEtco/create-an-issue@v2
-        if: steps.check-failure-after-soak-tests.outcome == 'failure'
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          filename: .github/issue-templates/FAILURE-DURING-SOAK-TESTS.md
-          update_existing: true
-      - name: Publish Issue if failed AFTER Soak Tests
-        uses: JasonEtco/create-an-issue@v2
-        if: steps.check-failure-after-soak-tests.outcome == 'failure'
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          filename: .github/issue-templates/FAILURE-AFTER-SOAK-TESTS.md
-          update_existing: true
-      - name: Check for Performance Degradation either DURING or AFTER Soak Tests
-        if: steps.check-failure-after-soak-tests.outcome == 'failure' || steps.check-failure-after-soak-tests.outcome == 'failure'
-        run: >-
-          echo 'Soak Tests failed, see the logs above for details';
-          exit 1;
+      # - name: Get number of CPUs
+      #   run: echo "::set-output name=NUM_OF_CPUS::$(nproc --all)"
+      #   id: get-num-of-cpus-step
+      # - name: Get a snapshot of metrics
+      #   run: >-
+      #     mkdir -p soak-tests/snapshots/${{ github.sha }};
+      #     for metric_kind in cpu-load memory-usage;
+      #     do
+      #       aws cloudwatch get-metric-widget-image --metric-widget "$(
+      #         cat ./.github/aws-cloudwatch-api-values/get-metric-widget-statistics/$metric_kind-metric-widget.json |
+      #         sed -e "s/<MINUTES_TO_RUN>/${{ env.MINUTES_TO_RUN }}/g" \
+      #             -e "s/<METRIC_PERIOD>/${{ env.HOSTMETRICS_COLLECTION_INTERVAL_IN_SECONDS }}/g" \
+      #             -e "s/<NUM_OF_CPUS>/${{ steps.get-num-of-cpus-step.outputs.NUM_OF_CPUS }}/g" \
+      #             -e "s/<LOGS_NAMESPACE>/$(echo ${{ github.repository }}/soak-tests | sed 's/\//\\\//g')/g" \
+      #             -e "s/<DIMENSION_1_VALUE>/$(echo ${{ env.PROCESS_COMMAND_LINE }} | sed 's/\//\\\//g')/g"
+      #       )" |
+      #       jq -r '.MetricWidgetImage' |
+      #       base64 -d > soak-tests/snapshots/${{ github.sha }}/${{ matrix.app-platform }}-${{ matrix.instrumentation-type }}-$metric_kind-results.png;
+      #     done
+      # - name: Commit snapshots to repository
+      #   uses: EndBug/add-and-commit@v7
+      #   with:
+      #     add: soak-tests/snapshots
+      #     branch: gh-pages
+      #     message: 'Adding Soak Tests Snapshots'
+      # - name: Move back to the main branch
+      #   run: git checkout main
+      # - name: Prepare Soak Test results as JSON output
+      #   run: >-
+      #     declare -a COMMON_API_PARAMETERS=(
+      #     --namespace ${{ github.repository }}/soak-tests
+      #     --start-time $(date -u -d '${{ env.MINUTES_TO_RUN }} minutes ago' +%FT%TZ)
+      #     --end-time $(date -u +%FT%TZ)
+      #     --period ${{ env.HOSTMETRICS_COLLECTION_INTERVAL_IN_SECONDS }}
+      #     --region ${{ env.AWS_REGION }}
+      #     --statistics Sum
+      #     --dimensions Name=process.command_line,Value='${{ env.PROCESS_COMMAND_LINE }}'
+      #     );
+      #     AVERAGE_CPU_LOAD=$(
+      #       aws cloudwatch get-metric-statistics "${COMMON_API_PARAMETERS[@]}" --metric-name process.cpu.time |
+      #       jq -r '{
+      #         Name: "Soak Test Average CPU Load",
+      #         Value: [.Datapoints[].Sum] | (add / length / ${{ env.HOSTMETRICS_COLLECTION_INTERVAL_IN_SECONDS }} / ${{ steps.get-num-of-cpus-step.outputs.NUM_OF_CPUS }} * 100),
+      #         Unit: "Percent"
+      #       }'
+      #     )
+      #     AVERAGE_VIRTUAL_MEMORY=$(
+      #       aws cloudwatch get-metric-statistics "${COMMON_API_PARAMETERS[@]}" --metric-name process.memory.virtual_usage |
+      #       jq -r "{
+      #         Name: \"Soak Test Average Virtual Memory Used\",
+      #         Value: [.Datapoints[].Sum] | (add / length / $(echo '2^20' | bc)),
+      #         Unit: \"Megabytes\"
+      #       }"
+      #     );
+      #     jq -n "[$AVERAGE_CPU_LOAD] + [$AVERAGE_VIRTUAL_MEMORY] | {benchmarks: .}" |
+      #     tee output.json
+      # - name: Report on Soak Test Averages results
+      #   uses: NathanielRN/github-action-benchmark@v1.8.2-alpha3
+      #   continue-on-error: true
+      #   id: check-failure-after-soak-tests
+      #   with:
+      #     name: Soak Test Results - sample-app-${{ matrix.app-platform }}-${{ matrix.instrumentation-type }}
+      #     tool: custombenchmark
+      #     output-file-path: output.json
+      #     github-token: ${{ secrets.GITHUB_TOKEN }}
+      #     max-items-in-chart: 100
+      #     alert-threshold: 1%
+      #     # Does not work as expected, see: https://github.com/open-telemetry/opentelemetry-python/pull/1478
+      #     # comment-always: true
+      #     fail-on-alert: true
+      #     auto-push: ${{ github.ref == 'refs/heads/main' }}
+      #     gh-pages-branch: gh-pages
+      #     benchmark-data-dir-path: soak-tests/per-commit-overall-results
+      # - name: Publish Issue if failed DURING Soak Tests
+      #   uses: JasonEtco/create-an-issue@v2
+      #   if: steps.check-failure-after-soak-tests.outcome == 'failure'
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      #   with:
+      #     filename: .github/issue-templates/FAILURE-DURING-SOAK_TESTS.md
+      #     update_existing: true
+      # - name: Publish Issue if failed AFTER Soak Tests
+      #   uses: JasonEtco/create-an-issue@v2
+      #   if: steps.check-failure-after-soak-tests.outcome == 'failure'
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      #   with:
+      #     filename: .github/issue-templates/FAILURE-AFTER-SOAK_TESTS.md
+      #     update_existing: true
+      # - name: Check for Performance Degradation either DURING or AFTER Soak Tests
+      #   if: steps.check-failure-after-soak-tests.outcome == 'failure' || steps.check-failure-after-soak-tests.outcome == 'failure'
+      #   run: >-
+      #     echo 'Soak Tests failed, see the logs above for details';
+      #     exit 1;
